### PR TITLE
Backport 2.28: Fix compiling AESNI in Mbed-TLS with clang on Windows

### LINKED ISSUE #8372: Error compiling AESNI in Mbed-TLS with clang on Windows
### Summary

clang does not have MSVS intrinsics, the pre-processor condition below does not cover this case if clang runs in MSVC compatibility mode
https://github.com/Mbed-TLS/mbedtls/blob/1ec69067fa1351427f904362c1221b31538c8b57/library/aesni.h#L42-L46
It should be
```c
#if defined(_MSC_VER) && !defined(__clang__)
/* Visual Studio supports AESNI intrinsics since VS 2008 SP1. We only support
 * VS 2013 and up for other reasons anyway, so no need to check the version. */
#define MBEDTLS_AESNI_HAVE_INTRINSICS
#endif
```

### System information

Mbed TLS version 2.28.5, 3.5.0
Operating system and version: Windows 10/11
Default configuration.
Compiler: LLVM clang, clang-cl

### Expected behavior

Built without errors.

### Actual behavior

Got many errors
```
/mbedtls/library/aesni.c:62:17: error: passing 'unsigned int[4]' to parameter of type 'int *' converts between pointers to integer types with different sign [-Werror,-Wpointer-sign]
        __cpuid(info, 1);
                ^~~~
C:\PROGRA~1\LLVM\lib\clang\16\include\intrin.h:60:17: note: passing argument to parameter here
void __cpuid(int[4], int);
                ^
/mbedtls/library/aesni.c:102:21: error: call to undeclared function '_mm_aesdec_si128'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
            state = _mm_aesdec_si128(state, *rk);
                    ^
/mbedtls/library/aesni.c:102:21: note: did you mean '_mm_and_si128'?
C:\PROGRA~1\LLVM\lib\clang\16\include\emmintrin.h:2611:46: note: '_mm_and_si128' declared here
static __inline__ __m128i __DEFAULT_FN_ATTRS _mm_and_si128(__m128i __a,
                                             ^
<...>
```

### Additional infromation

Fixing PRs will be offered soon.

### PR DESCRIPTION
**Pull request by sergio-nsk**
## Description

Fixes #8372. Does not conflict with #8339.

It can successfully compile w/ or w/o the clang options `-maes -mpclmul`.

The macro `__GNUC__` is not defined by Clang on Windows, thus use the macro `__clang__` for `-maes -mpclmul`.

## PR checklist

Please tick as appropriate and edit the reasons (e.g.: "backport: not needed because this is a new feature")

- [x] **changelog** not required
- [x] **backport** not required
- [x] **tests** not required

### CODE REVIEW

**Review by lpy4105 — CHANGES_REQUESTED** [review]
Minor code style issue.
Have you checked this work on `2.28` branch?

File: library/aesni.c [hunk 1]
```diff
@@ -191,7 +191,7 @@ void mbedtls_aesni_gcm_mult(unsigned char c[16],
                             const unsigned char a[16],
                             const unsigned char b[16])
 {
-    __m128i aa, bb, cc, dd;
+    __m128i aa = {0}, bb = {0}, cc, dd;
```
[the remark this answers is not in the document]
Comment (sergio-nsk) [reply library/aesni.c]: Fixed. BTW clang thought the variables were not initialized and raised errors with `-Werror`.

**Comment by sergio-nsk** [comment]
> Minor code style issue. Have you checked this work on `2.28` branch?

Yes, of course. I use the LTS, hence I fixed the compiling issue here and then in `developement`. It's now compiled well with MSVC, clang and clang -maes -mpclmul. The latter is not required in 2.28 like in `devlopement` https://github.com/Mbed-TLS/mbedtls/blob/development/library/aesni.h#L67-L72.

**Review by lpy4105 — APPROVED** [review]
LGTM

**Review by tom-cosgrove-arm — APPROVED** [review]
LGTM

**Review by tom-cosgrove-arm — APPROVED** [review]
LGTM

**Review by lpy4105 — APPROVED** [review]
LGTM

**Comment by sergio-nsk** [comment]
I don't know why my PR is kicked out the merge queue. How can I investigate it?

**Comment by lpy4105** [comment]
Merge queue failure seems to be spurious, need to resubmit.

**Comment by gilles-peskine-arm** [comment]
Weird infrastructure failure on the merge queue:
```
Channel "unknown": Remote call on container-host.eu-west-1b (i-007507a020fad60fb) failed. The channel is closing down or has closed down
```

This is a new error to me, but it seems to happen often since a day or two ago. Same error in https://github.com/Mbed-TLS/mbedtls/pull/8374.
