### PR TITLE
[Backport 3.6] Move some test helpers to the framework

### PR DESCRIPTION
**Pull request by davidhorstmann-arm**
Backport of #9756.

This contains all of the relevant commits from #9756. Some commits from that PR touch only TF-PSA-Crypto related parts so are not included.

Additionally there is one commit which is partly [taken from a previous development PR](https://github.com/Mbed-TLS/mbedtls/pull/9693/commits/924dca9d392aacb8edb61d056de1f168003c0007). This re-aligns 3.6 with development in test helpers after a change that was made.

## PR checklist

Please remove the segment/s on either side of the | symbol as appropriate, and add any relevant link/s to the end of the line.
If the provided content is part of the present PR remove the # symbol.

- [x] **changelog** not required because: Internal changes only - file motion 
- [x] **development PR** provided #9756 
- [x] **framework PR** provided Mbed-TLS/mbedtls-framework#65
- [x] **3.6 PR** here
- [x] **2.28 PR** not required because: No framework in 3.6
- **tests**  not required because: File motion only, existing testing will suffice

### CODE REVIEW

**Review by eleuzi01 — DISMISSED** [review]
LGTM, thanks!

**Review by eleuzi01 — DISMISSED** [review]

**Comment by mpg** [comment]
The CI is failing in multiple components. 
```
[2024-11-18T19:02:32.872Z]   CC    ../framework/tests/src/psa_exercise_key.c
[2024-11-18T19:02:32.872Z] ../framework/tests/src/psa_exercise_key.c:749:14: error: implicit declaration of function 'psa_key_agreement' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
[2024-11-18T19:02:32.872Z]     status = psa_key_agreement(key, public_key, public_key_length, alg,
[2024-11-18T19:02:32.872Z]              ^
[2024-11-18T19:02:32.872Z] ../framework/tests/src/psa_exercise_key.c:749:14: note: did you mean 'psa_raw_key_agreement'?
[2024-11-18T19:02:32.872Z] ../include/psa/crypto.h:4125:14: note: 'psa_raw_key_agreement' declared here
[2024-11-18T19:02:32.872Z] psa_status_t psa_raw_key_agreement(psa_algorithm_t alg,
[2024-11-18T19:02:32.872Z]              ^
[2024-11-18T19:02:32.872Z] 1 error generated.
```
The function `psa_key_agreement()` was added in development but is not present in 3.6. I guess we need some new `#if` guards here to avoid trying to use development-only functions in 3.6.

**Review by mpg — COMMENTED** [review]
LGTM, except for the test failures which needs to be resolved by changes to https://github.com/Mbed-TLS/mbedtls-framework/pull/78

**Review by mpg — APPROVED** [review]
LGTM, thanks!

**Review by eleuzi01 — APPROVED** [review]
LGTM
