### PR TITLE
psa_util.c included in builds without PSA, which can break the build

### LINKED ISSUE #9311: psa_util.c included in builds without PSA, which can break the build
In Mbed TLS 3.6.0, when `MBEDTLS_ECDSA_C` is enabled but `MBEDTLS_PSA_CRYPTO_C` is disabled, some code from `psa_util.c` is included and declares a 0-size array, resulting in a compilation error (except under some non-picky compilers). In this configuration, no code from `psa_util.c` should be included.

The culprit seems to be the definition of `MBEDTLS_PSA_UTIL_HAVE_ECDSA` in `include/mbedtls/config_adjust_legacy_crypto.h`:
```
#if defined(MBEDTLS_ECDSA_C) || (defined(MBEDTLS_PSA_CRYPTO_C) && \
    (defined(PSA_WANT_ALG_ECDSA) || defined(PSA_WANT_ALG_DETERMINISTIC_ECDSA)))
#define MBEDTLS_PSA_UTIL_HAVE_ECDSA
#endif
```

`MBEDTLS_PSA_UTIL_xxx` should be either undefined or ignored if `MBEDTLS_PSA_CRYPTO_C` isn't defined. (Or should this be `MBEDTLS_PSA_CRYPTO_CLIENT`?)

[Originally reported on the mailing list](https://lists.trustedfirmware.org/archives/list/mbed-tls@lists.trustedfirmware.org/thread/WGMVCPKOYERXFJWHKBK3Z47ERKTQMKLJ/)

Definition of done:

* When `MBEDTLS_PSA_CRYPTO_C` is disabled, no code from `psa_util.c` should be enabled.
* This should have been caught by the CI, in `component_test_no_psa_crypto_full_cmake_asan` and in some of the reference configurations. Figure out why it wasn't caught and fix that.

### PR DESCRIPTION
**Pull request by sezrab**
Introduced max size/bytes macros in psa_util.c. Prevents 0-size array compiler warning in psa-util.c when MBEDTLS_ECDSA_C is enabled but MBEDTLS_PSA_CRYPTO_C is disabled. Fixes #9311 

## PR checklist

- [x] **changelog** provided
- [x] **3.6 backport** provided, see #9463
- [x] **2.28 backport** not required, feature doesn't exist
- [x] **tests** not required because we removed buggy functions in configurations that made them buggy. See also #9317

### CODE REVIEW

File: library/psa_util.c [hunk 1]
```diff
@@ -365,6 +365,14 @@ int mbedtls_psa_get_random(void *p_rng,
```
Comment (gilles-peskine-arm) [inline library/psa_util.c:365]: We need either a non-regression test (i.e. a test that fails before applying the fix and passes after), or a good reason not to have one. Sometimes, “it's too much effort to write a test” can be a good reason.

Here I see two ways in which a test could catch the bug.

One way is at compile time: either we are never compiling in an affected configuration, or we are compiling in some affected configurations but only with permissive compiler flags (GCC and Clang allow 0-size array by defaults). According to the outcome file from https://github.com/Mbed-TLS/mbedtls/pull/9301 (I'm looking at the 3.6 outcomes, because in the `development` we're moving to PSA-only configurations where this bug can't happen), and with the help of `search_outcomes.py` from https://github.com/Mbed-TLS/mbedtls-framework/pull/20, I can see:
```
$ framework/scripts/search_outcomes_config.py -f outcomes-3.6.csv MBEDTLS_ECDSA_C \!MBEDTLS_PSA_CRYPTO_C
component_test_default_psa_crypto_client_without_crypto_provider
component_test_full_no_cipher_no_psa_crypto
component_test_no_psa_crypto_full_cmake_asan
config-no-entropy.h
config-suite-b.h
```

The first one has `MBEDTLS_PSA_CRYPTO_C` disabled but `MBEDTLS_PSA_CRYPTO_CLIENT` enabled, so it's actually not relevant here. The other 4 are relevant. The two configuration names ending with `.h` are handled by `tests/scripts/test-ref-configs.pl`, and they're just using the config files in the `configs` subdirectory. All of these builds use Clang (or maybe GCC) without `-std=c99 -pedantic`, so they don't complain about 0-length arrays. Ideally we should pass `-std=c99 -pedantic`, but I haven't checked if it's feasible without too much effort: it might cause a bunch of other errors that we don't want to deal with.

The second way to catch the bug would be through tests. After all, if we run a test that tries to use a 0-size array, the test would surely overflow that array. We do most test builds with [Asan](https://github.com/google/sanitizers/wiki/AddressSanitizer), which detects buffer overflows. Why wasn't there a test failure? We do have tests for these functions. They're in [`test_suite_psa_crypto_util`](https://github.com/Mbed-TLS/mbedtls/blob/mbedtls-3.6.0/tests/suites/test_suite_psa_crypto_util.data). The test function is only guarded by `MBEDTLS_PSA_UTIL_HAVE_ECDSA`, but the test data is guarded by a minimum value for `PSA_VENDOR_ECC_MAX_CURVE_BITS` for all test cases. If the functions are available in configurations where PSA is disabled, we need to change the guards on these tests, since `PSA_VENDOR_ECC_MAX_CURVE_BITS` is 0 when PSA is disabled.

So we now understand that we didn't catch this bug due to a test gap. And we need to fix the test gap here.

**Review by gilles-peskine-arm — CHANGES_REQUESTED** [review]
This is correct but incomplete.

Although it's correct, I'm not sure this is the right approach, between restricting the function definition and fixing the array sizes. Let's discuss this further with Manuel in the [issue](https://github.com/Mbed-TLS/mbedtls/issues/9311).

File: library/psa_util.c (hunk 1 above)
Comment (gilles-peskine-arm) [reply library/psa_util.c:365]: Note that in builds with PSA disabled, `PSA_WANT_xxx` symbols might still be set, so `PSA_VENDOR_ECC_MAX_CURVE_BITS` might still end up being nonzero. I haven't figured out exactly when it ends up being 0.

Comment (mpg) [reply library/psa_util.c:365]: > Ideally we should pass `-std=c99 -pedantic`, but I haven't checked if it's feasible without too much effort: it might cause a bunch of other errors that we don't want to deal with.

In the past we there were indeed some portions of our code that threw a lot of errors with those flags, but looking at `all.sh` it looks like nowadays we can use them with `config.py` full and build everything. So, I'm tempted to suggest we use `-std=c99 -pedantic` as our new default in `all.sh` (like, add it to `$ASAN_CFLAG` and cmake's ASan flags), and only disable it locally if there are a few components that don't work with it. Wdyt?

(@sezrab That would of course be out of scope for this PR and be a separate piece of work.)

Comment (gilles-peskine-arm) [reply library/psa_util.c:365]: > I'm tempted to suggest we use -std=c99 -pedantic as our new default in all.sh (like, add it to $ASAN_CFLAG and cmake's ASan flags), and only disable it locally if there are a few components that don't work with it

That's absolutely a good idea. The thing is, I have no idea how far we are from it, so I can't estimate how long it'll take, which means it's currently not feasible.

**Comment by mpg** [comment]
Unfortunately this grew a conflict. @sezrab Can you resolve the conflict, then ping Gilles and me, and we'll re-review shortly?

**Comment by mpg** [comment]
Aw, very unlucky, got a new conflict right after your rebased. Can you rebase again? Thanks!

File: tf-psa-crypto/core/psa_util.c [hunk 2]
```diff
@@ -365,7 +365,23 @@ int mbedtls_psa_get_random(void *p_rng,
 
 #endif /* MBEDTLS_PSA_CRYPTO_CLIENT */
 
-#if defined(PSA_HAVE_ALG_SOME_ECDSA)
+#if defined(MBEDTLS_PSA_CRYPTO_CLIENT)
```
Comment (mpg) [inline tf-psa-crypto/core/psa_util.c:368]: The only places where we're using these macros are guarded by `MBEDTLS_PSA_UTIL_HAVE_ECDSA` which now depends on `PSA_CRYPTO_CLIENT`.

I think there was some confusion about the strategy here: Gilles suggested we guard the functions with `PSA_CRYPTO_CLIENT`, then I suggested that we don't have to do that, we can instead introduce macros with different definitions depending on whether it's enabled... but later I was convinced by Gilles's argument that it's simpler to just remove the functions when PSA's not available. (Said otherwise: the two suggestions were mutually exclusive alternatives.)

Can you remove those macros, and just leave the part when `PSA_UTIL_HAVE_ECDSA` now depends on `PSA_CRYPTO_CLIENT`? (Plus the changes in test dependencies which are good as well.)

**Review by mpg — CHANGES_REQUESTED** [review]
I think this fixes the issue, but also does extra work that's no longer needed as the chosen fix was to remove those functions from non-PSA builds.

**Review by mpg — COMMENTED** [review]
The code looks good to me, thanks!

I think this needs a ChangeLog entry though, as it fixes a bug that was reported externally - which is a clear sign it was user-visible :) (Everything that's visible to normal users should get an entry.) If that's your first time adding an entry, see https://github.com/Mbed-TLS/mbedtls/blob/development/ChangeLog.d/00README.md

Suggested description of the issue: "When `MBEDTLS_PSA_CRYPTO_C` was disabled and `MBEDTLS_ECDSA_C` enabled, some code was defining 0-size arrays, resulting in compilation errors. Fixed by disabling the offending code in configurations without PSA Crypto, where it never worked. Fixes #9311".

**Review by mpg — APPROVED** [review]
LGTM, thanks!

**Review by gilles-peskine-arm — DISMISSED** [review]
LGTM

**Comment by mpg** [comment]
@sezrab Now that this is approved, can you create the 3.6 backport? Thanks!

File: include/mbedtls/config_adjust_legacy_crypto.h [hunk 3]
```diff
@@ -428,7 +428,7 @@
 
 /* psa_util file features some ECDSA conversion functions, to convert between
  * legacy's ASN.1 DER format and PSA's raw one. */
-#if defined(MBEDTLS_ECDSA_C) || (defined(MBEDTLS_PSA_CRYPTO_C) && \
+#if (defined(MBEDTLS_PSA_CRYPTO_CLIENT) && \
     (defined(PSA_WANT_ALG_ECDSA) || defined(PSA_WANT_ALG_DETERMINISTIC_ECDSA)))
 #define MBEDTLS_PSA_UTIL_HAVE_ECDSA
```
Comment (gilles-peskine-arm) [inline include/mbedtls/config_adjust_legacy_crypto.h:433]: In `development` today, `MBEDTLS_PSA_UTIL_HAVE_ECDSA` is still defined but never used. So there's a semantic conflict between what this pull request is doing and what has changed in `development`.

**Review by gilles-peskine-arm — CHANGES_REQUESTED** [review]
This pull request has a semantic conflict with changes in the `development` branch: it changes the definition of `MBEDTLS_PSA_UTIL_HAVE_ECDSA`, but `MBEDTLS_PSA_UTIL_HAVE_ECDSA` is no longer used in `development`. 

In `develompent` now, we're removing support for builds without PSA. The library functions are now guarded by `PSA_HAVE_ALG_SOME_ECDSA`, no longer by `MBEDTLS_PSA_UTIL_HAVE_ECDSA`. The test functions are also guarded by `PSA_HAVE_ALG_SOME_ECDSA`. So the bug is resolved in `development`, although we hadn't noticed that there was a bug so we should still announce it in a changelog entry. (This changelog entry will need to change because it's referring to non-PSA builds, which will no longer be a thing. But I expect that we'll handle these changes to changelog entries in bulk at the end of the de-non-PSA-ification work.)

In addition to the changelog entry, we should remove the unused definition of `MBEDTLS_PSA_UTIL_HAVE_ECDSA`. Having this unused definition created confusion. For example, if the definition had been removed, there would have been a git conflict with this pull request, which would have alerted us that there was a conflict.

**Comment by mpg** [comment]
> should still announce it in a changelog entry.

As a general principle I would agree. But in this case, since the bug was only when PSA is disabled, and in 4.0 PSA will always be on, does it really make sense to have a ChangeLog entry for this in 4.0? The following would seem weird to me:
```
Changes
    * PSA Crypto is always enabled.
Bugfix
    * Fix compile error when PSA is disabled by removing the offending functions when PSA is disabled.
```

> we should remove the unused definition of MBEDTLS_PSA_UTIL_HAVE_ECDSA. Having this unused definition created confusion. For example, if the definition had been removed, there would have been a git conflict with this pull request, which would have alerted us that there was a conflict.

Agreed, though [I think that's a job for 9384's author](https://github.com/Mbed-TLS/mbedtls/pull/9384#discussion_r1713327315).

So overall, I'd be inclined to just close this development PR, and keep the "backport" as a 3.6-only PR, changing the description to add "PR development: not required because: bug defined out of existence in 4.0".

Wdyt?

**Comment by gilles-peskine-arm** [comment]
> As a general principle I would agree. But in this case, since the bug was only when PSA is disabled, and in 4.0 PSA will always be on, does it really make sense to have a ChangeLog entry for this in 4.0? The following would seem weird to me:

I expect that many changelog entries for bug fixes will not look right for the 4.0 release because they've been overridden. Sometimes they'll be overridden in ways that we don't anticipate yet because we don't know all the details of 4.0. We'll need to go over changelog entries and reword the ones that need rewording, including but not limited to removing the ones that are completely obsolete. That's a lot easier than going through the whole lot of commits and figuring out everything we need to announce.

So no, please don't skip changelog entries for bug fixes just because you think they'll go away later.

> Agreed, though I think that's a job for 9384's author.

I don't care who does it. We're a team. If there's a reason for it to stay for now, then of course it should stay. But then we should add a comment to explain why it's staying!

**Comment by mpg** [comment]
> So no, please don't skip changelog entries for bug fixes just because you think they'll go away later.

Ok then. In that specific instance I think we don't just think it'll go away, we know it, because PSA always on is one of the defining features of 4.0. OTOH, you're right that in other cases things will be less clear, and it's better to have a uniform process with no exception, so let's add the ChangeLog now even though it's extremely likely to be removed later. (Btw, do we have an issue to track that step when preparing the 4.0 release?)

> I don't care who does it. We're a team.

Sure. I meant for another PR. My line of thinking was whether we still needed this PR at all. Since we're doing the ChangeLog entry anyway, then the question is moot.

**Comment by gilles-peskine-arm** [comment]
> (Btw, do we have an issue to track that step when preparing the 4.0 release?)

Not yet. So far I've avoided creating 4.0 issues that aren't ready for work yet, to avoid noise during planning. I've only created a few because they were direct follow-ups to tasks that are started or ready to start.

File: tf-psa-crypto/tests/suites/test_suite_psa_crypto_util.function [hunk 4]
```diff
@@ -3,7 +3,7 @@
 #include <mbedtls/psa_util.h>
 /* END_HEADER */
 
-/* BEGIN_CASE depends_on:PSA_HAVE_ALG_SOME_ECDSA */
+/* BEGIN_CASE depends_on:MBEDTLS_PSA_UTIL_HAVE_ECDSA */
```
Comment (mpg) [inline tf-psa-crypto/tests/suites/test_suite_psa_crypto_util.function:6]: #9384 has been replacing and we shouldn't be undoing that here. Please remove the changes to the test files (which were correct at the time you made them, btw, but development is moving fast these days).

**Comment by mpg** [comment]
Just to summarize, I think this PR should be ChangeLog only:
- no need to change the definition of `MBEDTLS_PSA_UTIL_HAVE_ECDSA` as it's no longer used and will be removed by #9396 (soon, hopefully);
- no need to change the macro used in the tests as it's now correct thanks to changes that have happened in development in the meantime.

(For the avoidance of doubt: that's just for the development PR. The 3.6 PR is fine as it is and keeps the fixes to the definition and tests in addition to the ChangeLog.)

**Review by gilles-peskine-arm — APPROVED** [review]
Approved with just the changelog because we need the 3.6 PR in the upcoming release, but I would strongly prefer to either remove the definition of `MBEDTLS_PSA_UTIL_HAVE_ECDSA` or edit its comment to state that it shouldn't be used anymore and explain why it's still there.

**Review by mpg — APPROVED** [review]
