### PR TITLE
Test with TF-M config and p256-m driver (part 1)

### LINKED ISSUE #8006: Test with TF-M config, p256-m driver, and no bignum
Add a pair of components to all.s, somewhat similar to the one added in #7754 (that is, all ECC accelerated, no bignum) except:
- instead of starting with `crypto_full` it starts with the TF-M config (see below)
  - as a result, fewer adjustments should be needed (RSA and FFDH already disabled, etc.)
  - note: EC J-PAKE is disabled, so does not need accelerating
- instead of using libtestdriver1, use p256-m as the driver for ECDH and ECDSA (see config.h option `MBEDTLS_P256M_EXAMPLE_DRIVER_ENABLED`) - so, we won't use `helper_libtestdriver1` functions for this build.

The TF-M config is enabled by doing:
```sh
    cp configs/tfm_mbedcrypto_config_profile_medium.h "$CONFIG_H"
    cp configs/crypto_config_profile_medium.h "$CRYPTO_CONFIG_H"
```
(see `component_build_tfm_armcc()` for example).

Fix any issue that might arise and get testing parity.

### PR DESCRIPTION
**Pull request by valeriosetti**
Opening this PR as draft for multiple reasons:

- P256M does not support import/export of keys, so I had to enable the builtin support for those operations
    - builtin support means enabling `ECP_C` and `BIGNUM_C` which is not the purpose of #8006
- P256M also does not support deterministic ECDSA so also this part is builtin
- there are some symbols missing from the default TFM configuration file, which were added in the `cflag` variable in the test. Is this expected?

BTW the component builds and all the test suites pass.

~Depends on #7992~
Depends on https://github.com/Mbed-TLS/mbedtls/pull/8164
First step towards #8006 - will be complete by #8041

## PR checklist

- [x] **changelog** not required - test only
- [x] **backport** not required - test for a new feature
- [x] **tests** provided

### CODE REVIEW

File: tests/scripts/all.sh [hunk 1]
```diff
@@ -2633,6 +2629,235 @@ component_test_psa_crypto_config_reference_ecc_no_ecp_at_all () {
...
+    # support these operations.
+    loc_accel_list="ALG_ECDSA \
+                    ALG_ECDH \
+                    KEY_TYPE_ECC_KEY_PAIR_BASIC \
+                    KEY_TYPE_ECC_KEY_PAIR_GENERATE \
+                    KEY_TYPE_ECC_PUBLIC_KEY"
+    loc_accel_flags="$( echo "$loc_accel_list" | sed 's/[^ ]* */-DMBEDTLS_PSA_ACCEL_&/g' )"
+
+    # Build crypto library specifying we want to use P256M code for EC operations
+    make CFLAGS="$loc_accel_flags -DMBEDTLS_P256M_EXAMPLE_DRIVER_ENABLED"
```
Comment (mpg) [inline tests/scripts/all.sh:2831]: Note: I feel we should build with ASan here (like we do for other driver builds).

Comment (valeriosetti) [reply tests/scripts/all.sh:2831]: I tried to add `ASAN_CFLAGS` to the build, but there seems to be a runtime error related to the `-fsanitize=undefined` option:
```
memory_buffer_alloc.c:311:15: runtime error: member access within misaligned address 0x7ffdcab0144c for type 'struct memory_header', which requires 8 byte alignment
```

Comment (mpg) [reply tests/scripts/all.sh]: Ah right, so there's a compromise here, we can either:
1. test with ASan and disable `BUFFER_ALLOC_C` for maximum ASan efficiency, at the expense of similarity with the TF-M config;
2. test with ASan and `BUFFER_ALLOC_C` for maximum similarity with TF-M config, at the expense of ASan efficiency (it would still check stack buffers and static ones, and we'd still have UBSan enabled); 
3. keep `BUFFER_ALLOC_C` and don't bother with ASan.

I don't think (3) has much merit, and I'd actually be inclined to go for (1). IMO we want to test a config that's identical to TF-M's in terms of crypto features, but we don't care as much about platform-type things - we are already modifying some of them anyway. But I'm open to argument for (2).

Comment (valeriosetti) [reply tests/scripts/all.sh]: Side note, since I faced this problem yesteday when I  tried to address this comment before @gilles-peskine-arm's suggestion. In case we go for option (2) the `MBEDTLS_MEMORY_ALIGN_MULTIPLE` should be set to 8 bytes in 64 bit architectures otherwise tests fail due to wrong alignment.

Comment (tom-cosgrove-arm) [reply tests/scripts/all.sh]: I think we want maximum ASan efficiency for these tests

**Comment by valeriosetti** [comment]
Rebased after #7992 was merged

File: tests/scripts/all.sh [hunk 2]
```diff
@@ -2780,6 +2780,104 @@ component_test_psa_crypto_config_reference_ecc_no_bignum () {
...
+# - component_test_tfm_config()
+common_tfm_config () {
+    # Enable TF-M config
+    cp configs/tfm_mbedcrypto_config_profile_medium.h "$CONFIG_H"
+    cp configs/crypto_config_profile_medium.h "$CRYPTO_CONFIG_H"
+
+    # Adjust for the fact that we're building outside the TF-M environment.
+    #
+    # TF-M has separation, our build doesn't
+    scripts/config.py unset MBEDTLS_PSA_CRYPTO_SPM
```
Comment (gilles-peskine-arm) [inline tests/scripts/all.sh:2794]: Having just gotten bitten by this, I don't like the fact that the configuration in `configs` can't be built. The problem is that we can't do a build with `MBEDTLS_PSA_CRYPTO_SPM` without some third-party files — the library build succeeds but the tests fail:
```
In file included from tests/include/test/psa_crypto_helpers.h:27,
                 from tests/src/psa_crypto_helpers.c:26:
tests/include/test/psa_helpers.h:25:10: fatal error: spm/psa_defs.h: No such file or directory
   25 | #include "spm/psa_defs.h"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
```

It's also weird that we're not using `test-ref-configs` like we do for all the other configurations in the `configs` directory.

I think the files need to be reorganized. The `configs` directory should contain files that work on their own. Proposal:

* Move `tfm_mbedcrypto_config_profile_medium.h` and `crypto_config_profile_medium.h` to a subdirectory (and perhaps rename them). Note that we don't want to change these files because they're copies of the files from TF-M.
* Create a `configs/config-tfm.h` that:
    1. includes the TF-M mbedtls config file;
    2. sets `MBEDTLS_PSA_CRYPTO_CONFIG_FILE` to point to the TF-M psa crypto config file;
    3. unsets `MBEDTLS_PSA_CRYPTO_SPM`, and whatever else is needed to build .
* Add `configs/config-tfm.h` to `test-ref-configs.pl`.
* Create a file under `tests/configs` that arranges the exact TF-M configuration that we're using for code size measurements. This one doesn't need to produce working executables.

Comment (tom-cosgrove-arm) [reply tests/scripts/all.sh:2794]: Agreed, these files should not be in that directory. I'd rather not have a wrapper for them, but I do want to change how we handle them, so that the original content is undisturbed at the top and our modifications are clearly separate - the TF-M config files need to change, and having a wrapper to "set/unset ... whatever else is needed to build" is such a tight coupling between the two files in that proposed split I'd rather not have it in two files

Comment (tom-cosgrove-arm) [reply tests/scripts/all.sh:2794]: @yanrayw ^

**Comment by mpg** [comment]
Closing as the work will be continued in #8041 which includes this one.

File: tests/scripts/all.sh (hunk 1 above)
Comment (mpg) [reply tests/scripts/all.sh]: Marking as resolved as this has been done: https://github.com/Mbed-TLS/mbedtls/pull/8041/files#diff-e683396c93d3af1ea2db5a3d94788da3916ed084f3eb8be5e5f7c0e429badf39R2820

File: tests/scripts/all.sh (hunk 2 above)
Comment (mpg) [reply tests/scripts/all.sh:2794]: Marking as resolved by @yanrayw's PR - thanks!
