### ISSUE TITLE
AES-NI compilation on x86

### ISSUE THREAD

**Issue by beni-sandu** [Mbed-TLS/mbedtls#8400]
### Summary

AES-NI does not compile by default on x86 with either gcc/clang

### System information

Mbed TLS version (number or commit id): **3.5.0**
Operating system and version: **Linux Ubuntu 22.04**
Configuration (if not default, please attach `mbedtls_config.h`): **default**
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): **i686 gcc from default repo**
Additional environment information: 

### Steps to reproduce
```
$ CC="i686-linux-gnu-gcc-11" make -C library/

  CC    aes.c
In file included from aes.c:61:
aesni.h:69:5: error: #error "Must use `-mpclmul -msse2 -maes` for MBEDTLS_AESNI_C"
   69 | #   error "Must use `-mpclmul -msse2 -maes` for MBEDTLS_AESNI_C"
      |     ^~~~~
make: *** [Makefile:313: aes.o] Error 1
```

### Additional information
Discovered during yocto CI build for x86: https://errors.yoctoproject.org/Errors/Details/739887/

I am trying to get some extra info on this. Having a quick look in aesni.h, I see that inline assembly is only supported on 64bit, and intrinsics is the default for 32bit, which requires the extra flags passed to compiler. Is it expected that the user will always pass these flags when building 32bit variants?

I don't know the history/plan here, but I think most users would expect that everything builds out of the box, without fiddling with extra flags.

Note: Library builds fine on both gcc/clang when passing the flags.

Please let me know if I am misunderstanding something.

Thanks,
Beni

**Comment by tom-cosgrove-arm** [comment]
Note: introduced by #7384

**Comment by tom-daubney-arm** [comment]
Hi Beni,

Thanks for the report. This issue looks to be a duplicate of #8334 and so I will be closing this issue.
